project:
  type: website

website:
  title: "Tengfei"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: certificate/index.qmd
        text: Certificate
      - href: gallery/index.qmd
        text: Gallery
      - href: about/index.qmd
        text: About
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/tengfei
        text: LinkedIn
      - icon: twitter
        href: https://twitter.com/tengfei
        text: Twitter
      - icon: github
        href: https://github.com/tengfei
        text: GitHub
  google-analytics: "G-VE3DTZ3QX8"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



